# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Clone repo
      uses: actions/checkout@v4
      
    - name: Clone coredns
      run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/coredns/coredns.git coredns_main
          
    - name: Merge this repo and coredns
      run: cp -R coredns/plugin/* coredns_main/plugin/
    
    - name: Enable plugin dns64_hack
      run: sed '/dns64:dns64/a dns64_hack:dns64_hack' coredns_main/plugin.cfg >> coredns_main/plugin.cfg1 && mv coredns_main/plugin.cfg1 coredns_main/plugin.cfg
      
    - name: Enable plugin cut_cname
      run: sed '/dns64_hack:dns64_hack/a cut_cname:cut_cname' coredns_main/plugin.cfg >> coredns_main/plugin.cfg1 && mv coredns_main/plugin.cfg1 coredns_main/plugin.cfg
      
    - name: Enable plugin dmatcher
      run: sed '/local:local/a dmatcher:dmatcher' coredns_main/plugin.cfg >> coredns_main/plugin.cfg1 && mv coredns_main/plugin.cfg1 coredns_main/plugin.cfg
      
    - name: Enable plugin finalize
      run: sed '/view:view/a finalize:github.com/tmeckel/coredns-finalizer' coredns_main/plugin.cfg >> coredns_main/plugin.cfg1 && mv coredns_main/plugin.cfg1 coredns_main/plugin.cfg
      
    - name: Build
      run: make -C coredns_main/
      
    - name: Copy bin to release
      run: mkdir ../release && cp coredns_main/coredns ../release && chmod +x ../release/coredns

    - name: Copy templates to release
      run: cp -r coredns/templates ../release

    - name: Copy www_static to release
      run: cp -r coredns/www_static ../release
    
    - name: Copy systemd unit to release
      run: cp -r systemd/coredns.service ../release

    - name: Create archive
      run: tar czf release.tar.gz ../release/

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release.tar.gz
        asset_name: linux-x64-systemd.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: "auto build"

